[package]
name = "sludge"
version = "0.1.52"
edition = "2021"

[dependencies]
include_directory = { version = "0.1.1", optional = true }
hashmap_macro = "0.1.0"
macroquad = "0.4.14"

[features]
bundled = ["dep:include_directory"]
